workflows:
  # Workflow para iOS
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build iOS (no code signing)
        script: |
          flutter build ios --release --no-codesign
      - name: Create unsigned IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r NequiKill-unsigned.ipa Payload
          rm -rf Payload
    artifacts:
      - NequiKill-unsigned.ipa
      - build/ios/iphoneos/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - sxngre@github.com
        notify:
          success: true
          failure: true
  
  # Workflow para Android
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - sxngre@github.com
        notify:
          success: true
          failure: true
